//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lessons
    {
        public int IdLesson { get; set; }
        public int GroupId { get; set; }
        public string DayOfWeek { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public int SubjectId { get; set; }
        public int TeacherId { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
