//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PC()
        {
            this.Rents = new HashSet<Rents>();
        }
    
        public int IdPC { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public string Status { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<System.DateTime> RentDate { get; set; }
        public Nullable<int> Hours { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual PC_Types PC_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rents> Rents { get; set; }
    }
}
