//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rents
    {
        public int IdRent { get; set; }
        public int ClientId { get; set; }
        public int IdPC { get; set; }
        public int AdminId { get; set; }
        public System.DateTime RentDate { get; set; }
        public int Hours { get; set; }
        public int Price { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual PC PC { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
